spring:
  application:
    name: File-Management-System
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/fms?serverTimezone=Asia/Kuala_Lumpur"
    username: "root"
    password: "1234"
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
        timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 9090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true

logging:
  level:
    com.fms.fmsback.controller: INFO
    org.springframework: INFO