spring:
  application:
    name: File-Management-System
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/fms?serverTimezone=Asia/Kuala_Lumpur"
    username: "root"
    password: "1234"

server:
  port: 9090

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.commons.JakartaCommonsLoggingImpl
    map-underscore-to-camel-case: true

pagehelper:
  propertyName: propertyValue
  reasonable: false
  defaultCount: true

logging:
  level:
    com.fms.fmsback.controller: INFO
    org.springframework: INFO